---
title       : Citi Bike Sharing App
subtitle    : Changing The World One Bike Sharer at a Time
author      : Johan Edvinsson
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : brown_paper      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
assests : ../assets
logo    : header-logo.png
--- .class1 

## Citi Bike Sharing App

* The Citi Bike program is a bike sharing program, operating in New York City since the summer of 2013. 
* Bike sharing allows for easy access to bikes without having to worry about the hassle of maintaining your bike or your bike getting stolen.
* Bike sharing can dramatically reduce emissions from motor vehicles and provides exercise that combat obesity and diabetes.
 

--- .class #id 

## Let's Look at the (Fake) Data

It is clear that the increase in bike share participation correlates with a decrease in both obesity and reduced emissions.

```{r, fig.width=10,fig.height=5.5, fig.align="center",echo=FALSE}
library(ggplot2)
set.seed(3)
x<-seq(as.Date("2000-01-01"),as.Date("2014-06-01"),by="month")
Label<-rep(c("Bike Sharers","Obesity","Emissions"),each=174)
x1<-1:174
y1<-0.5/(1+exp(-(x1-mean(x1))/40))+rnorm(174,mean=0,sd=0.02)
y2<-0.5-y1+rnorm(174,mean=0,sd=0.02)
y3<-1-y1+rnorm(174,mean=0,sd=0.02)
plotdf<-data.frame(Date=rep(x,3),Y=c(y1,y2,y3),Label=Label)
ggplot(data=plotdf)+geom_line(aes(x=Date,y=Y,group=Label,colour=Label))+ylab("Fraction of Population/ Normalized Emissions")+theme(axis.title=element_text(face="bold",size="12")) 
```
                (Generated from R expression in the slide code.)

--- .class #id 
## Citi Bike Sharing App
  
  
* The Citi Bike program is a bike sharing program, operating in New York City since the summer of 2013. 
* Bike sharing allows for easy access to bikes without having to worry about the hassle of maintaining your bike or your bike getting stolen.
* Bike sharing can dramatically reduce emissions from motor vehicles and provides exercise. 
   
   
## Getting more people to participate in bike sharing programs will provide huge benefits to humanity.

--- .class #id 
## Citi Bike Sharing App

* Citi Bike Sharing App allows the user to explore Citi Bike user data in a fun interactive way.
* The user can see traveling patterns in their neighborhoods, see how long it takes other users to bike to different locations.
* Will engage the user and encourage them to try the Citi Bike program.
* Is easy to use with instructions on the website and can be used by tourists, locals, young, and old alike.

* Go to the [CitiBike App](https://johanmedvinsson.shinyapps.io/CitiBike/) to try it out.

Disclaimers: 
        1. I am not affiliated with Citi Bike nor do they endorse my application.
        2. Although I think bike sharing programs are great and that they do offers many benefits the claims made here are exaggerated to say the least as are the claims of the utility of the app.
        

--- .class #id



